name: 🚀 IaC & Cloud Deploy (Render)

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    name: 'Terraform Plan & Apply'
    runs-on: ubuntu-latest
    # Pasamos los secretos de GitHub a Terraform
    env:
      TF_VAR_render_api_key: ${{ secrets.RENDER_API_KEY }}
      TF_VAR_render_owner_id: ${{ secrets.RENDER_OWNER_ID }}

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Apply
        # Aplica los cambios en Render automáticamente
        run: terraform -chdir=terraform apply -auto-approve